[general]
import = ["~/Themes/alacritty/colors/base16-papercolor-light.toml"]

[font]
size = 16

[font.normal]
family = "Source Code Pro"

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;6u"
key = "Tab"
mods = "Control|Shift"
